[package]
name = "os"
version = "0.1.0"
authors = ["Cliff L. Biffle <code@cliffle.com>"]
edition = "2018"

[dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
futures = { version = "0.3.5", default-features = false }
pin-utils = "0.1.0"
as-slice = "0.1.3"

# Mostly for examples
[dev-dependencies]
panic-halt = "0.2.0"

[dev-dependencies.stm32f4]
default-features = false
features = ["rt", "stm32f407"]
version = "0.11.0"

[lib]
test = false
bench = false
