[package]
name = "os"
version = "0.1.0"
authors = ["Cliff L. Biffle <code@cliffle.com>"]
edition = "2018"

[dependencies]
core = { path = "../corehack", package = "corehack", version = "0.1.0" }
cortex-m = "0.6"
cortex-m-rt = "0.6.10"
futures-preview = {version = "=0.3.0-alpha.19", default-features = false}
pin-utils = "0.1.0-alpha.4"
as-slice = "0.2.0"

[lib]
test = false
bench = false
