[package]
name = "os"
version = "0.1.0"
authors = ["Cliff L. Biffle <code@cliffle.com>"]
edition = "2018"

[dependencies]
cortex-m = "0.6"
cortex-m-rt = "0.6.10"
futures = {version = "0.3", default-features = false}
pin-utils = "0.1.0-alpha.4"
as-slice = "0.2.0"

# Mostly for examples
[dev-dependencies]
panic-halt = "0.2.0"

[dev-dependencies.stm32f4]
default-features = false
features = ["rt", "stm32f407"]
version = "0.8.0"

[lib]
test = false
bench = false
